### ISSUE TITLE
Suggestion : add pruned data amount on TG report

### ISSUE THREAD

**Issue by Valcyclovir** [calr0x/OT-NodeWatch#1]
Current TG notification : 
OTNODE: Forget command SUCCEEDED
OTNODE: Prune command SUCCEEDED
OTNODE: Check command SUCCEEDED

Suggestion :
Add a more detailed infographic to include amount of data pruned and how many nodes have been pruned to make sure it actually succeeded

**Comment by calr0x** [comment]
Suggestion as been added! as of 6/12/2021!

Thx B!
