### ISSUE TITLE
Disk check.sh refers to disk_space.sh

### ISSUE THREAD

**Issue by hottogo** [calr0x/OT-NodeWatch#11]
- name: Install **disk_space.sh**
      copy:
        src: ~/OT-NodeWatch/disk_check/disk_check.sh
        dest: /root/OT-NodeWatch/disk_check/disk_check.sh
        owner: root
        group: root
        mode: '0700'

Need to update to:

- name: Install disk_check.sh
      copy:
        src: ~/OT-NodeWatch/disk_check/disk_check.sh
        dest: /root/OT-NodeWatch/disk_check/disk_check.sh
        owner: root
        group: root
        mode: '0700'

**Comment by calr0x** [comment]
Great catch!

**Comment by calr0x** [comment]
Applied!
