### ISSUE TITLE
bid_check false alarm when logs not showing accepting

### ISSUE THREAD

**Issue by Valcyclovir** [calr0x/OT-NodeWatch#3]
Situation : 
Jobs sometimes do not show Accepting offer with price: xxxx TRAC, and therefore is not detected by the script used by bid_check.sh
the word chosen seems to give more accurate results

Temporary solution : 
change line to 
docker logs --since $BID_INTERVAL otnode | grep chosen | wc -l

**Comment by calr0x** [comment]
Applied!
