### ISSUE TITLE
TG notification very spammy

### ISSUE THREAD

**Issue by Valcyclovir** [calr0x/OT-NodeWatch#4]
Situation : 
TG notification for no job detection every 15 minutes is working as intended, but the notification spam when jobs are scarce is annoying and hard to filter through.

Suggestion : 
Instead of showing individual notifications from each node, have the notifications grouped up in a way that's easier to read and not as spammy, such as :
(X+Y+Z)/total nodes (X, Y, Z) have not had a job detected in the past 15 minutes.

**Comment by calr0x** [comment]
This one's a doozy but is def on the roadmap!

**Comment by calr0x** [comment]
Changed the default to 1mhour which is much more sane. Long term I will have a summary sent to the user or, in dreamland, it will populate a db we can then do cool shit to...

Closing this issue in the meantime!
