### ISSUE TITLE
Bid check Missing ansible instructions

### ISSUE THREAD

**Issue by hottogo** [calr0x/OT-NodeWatch#5]
Need to run:
ansible-playbook install-bid-check.yml

When finished updating configs to apply changes to all nodes from ansible. 

Other instructions also missing for ansible like editing install-bid-check.yml:
nano install-bid-check.yml

and lastly editing bid_check.sh:
nano bid_check.sh

**Comment by calr0x** [comment]
Thx Hot!

**Comment by calr0x** [comment]
The instructions for Ansible are located in each modules directory and in the ansible directory. Each modules playbook installs just that single component and, in the ansible directory, it installs all of the modules.

My expectation is an ansible user will know how to install a play book. I will always put what settings can be changed and the instructions at the top of each modules playbook!
