### ISSUE TITLE
install-disk-check.yml refers to the wrong files for ansible

### ISSUE THREAD

**Issue by hottogo** [calr0x/OT-NodeWatch#7]
need to change install-disk-check.yml file with nano to have the correct file path to the following:

        src: ~/OT-NodeWatch/disk_check/disk_check.sh
        dest: /root/OT-NodeWatch/disk_check/disk_check.sh

**Comment by hottogo** [comment]
install-disk-check.yml is also missing the permissions, I had to edit permissions in my nodes for the bidcheck folder so the exectuable could run when I did a test in the node.

See this section in smoothbrain:

- name: Set files to be executable file: path: '{{ item }}' mode: '0700' loop: - '/root/OT-Smoothbrain-Backup/data/link-merged.sh' - '/root/OT-Smoothbrain-Backup/data/send.sh' - '/root/OT-Smoothbrain-Backup/restic' - '/root/OT-Smoothbrain-Backup/restic-backup.sh' - '/root/OT-Smoothbrain-Backup/restic-cleanup.sh'
- 
Credit to Harold

**Comment by haroldboom** [comment]
Changes in bold, I think that should fix it! Thanks Calvin


- name: Install Monitor
  hosts: all
  vars:
    diskcheck_minute: '0' # Checks every day
    diskcheck_hour: '*'
    diskcheck_day: '*'
    diskcheck_month: '*'
    diskcheck_weekday: '*'
  gather_facts: no

  tasks:
    - name: Clone OT-NodeWatch git repository
      git:
        repo: 'https://github.com/calr0x/OT-NodeWatch.git'
        dest: /root/OT-NodeWatch
        force: yes

    - name: Install disk_space.sh
      copy:
        **src: ~/OT-NodeWatch/disk_check/disk_check.sh
        dest: /root/OT-NodeWatch/disk_check/disk_check.sh**
        owner: root
        group: root
        **mode: '0700'**

    - name: Delete existing monitor (docker check) schedule from cron
      cron:
        name: Monitor Disk Check
        state: absent

    - name: Add monitor (disk check) schedule to cron (once a day)
      cron:
        name: Monitor Disk Check
        minute: "{{ diskcheck_minute }}"
        hour: "{{ diskcheck_hour }}"
        day: "{{ diskcheck_day }}"
        month: "{{ diskcheck_month }}"
        weekday: "{{ diskcheck_weekday }}"
        **job: "/root/OT-NodeWatch/disk_check/disk_check.sh"**

**Comment by calr0x** [comment]
Applied!

Thx guys!
