### ISSUE TITLE
install-disk-check.yml overwritting config.sh

### ISSUE THREAD

**Issue by Valcyclovir** [calr0x/OT-NodeWatch#8]
Running ansible-playbook install-disk-check.yml overwrites config.sh settings

Solution : 
add the following on line 27 : 
    - name: Install config.sh
      copy:
        src: ~/OT-NodeWatch/config.sh
        dest: /root/OT-NodeWatch/config.sh
        owner: root
        group: root
        mode: '0600'

**Comment by calr0x** [comment]
Fixed!

Thanks B!
