### ISSUE TITLE
bid_check.sh improvements

### ISSUE THREAD

**Issue by Valcyclovir** [calr0x/OT-NodeWatch#9]
bid_check.sh currently verifies that our nodes accept jobs and notifies us when we get a  job

Suggestion :
Improve the "job rewarded" feature by adding the amount of trac won and holding time.

**Comment by calr0x** [comment]
Great idea and is totally doable!

**Comment by calr0x** [comment]
Done!

Falcor7: Job awarded: 180 days at 3.216036033971656700 TRAC

Check bid_check directory!

This ONLY works on dockerless installations!
